---
# Percona Server for MongoDB setup
- name: Setup Percona Server 8.4 and higher. Cluster with Group Replication in Docker
  hosts: localhost
  connection: local
  gather_facts: yes
  vars:
    psmdb_version: "{{ (lookup('env', 'PSMDB_VERSION') | default('7.0', true)) | replace('.', '_') }}"
    network_name: "pmm-qa"
    psmdb_container:
    nodes_count: "{{ (lookup('env', 'NODES_COUNT') | default('1', true)) | int }}"
    pmm_user: "pmm_mongodb"
    pmm_user_password: "5M](Q%q/U+YQ<^m"
    pmm_server_ip: "{{ lookup('vars', 'extra_pmm_server_ip', default=lookup('env','PMM_SERVER_IP') | default('127.0.0.1', true) ) }}"
    client_version: "{{ lookup('vars', 'extra_client_version', default=lookup('env','CLIENT_VERSION') | default('3-dev-latest', true) ) }}"
    admin_password: "{{ lookup('vars', 'extra_admin_password', default=lookup('env','ADMIN_PASSWORD') | default('admin', true) ) }}"
    setup_type: "{{ lookup('env', 'MONGO_SETUP_TYPE') }}"

  tasks:
  - name: Create pmm-qa network if not exist
    shell: docker network create {{ network_name }}
    ignore_errors: true

  - name: Prepare Container for Percona Server for MongoDB
    shell: |
      docker run --rm -d --name="psmdb_pmm_{{ psmdb_version }}_{{ item }}" \
      --network="pmm-qa" \
      --privileged --cgroupns=host -v /sys/fs/cgroup:/sys/fs/cgroup:rw \
      -v /var/lib/containerd \
      -v ./ssl:/ssl \
      antmelekhin/docker-systemd:rockylinux-9
    loop: "{{ range(1, nodes_count | int + 1) | list }}"

  - name: Install dependencies
    shell: |
      docker exec psmdb_pmm_{{ psmdb_version }}_{{ item }} dnf install -y openssl
    loop: "{{ range(1, nodes_count | int + 1) | list }}"

  - name: Install Percona Release
    shell: |
      docker exec psmdb_pmm_{{ psmdb_version }}_{{ item }} wget https://repo.percona.com/yum/percona-release-latest.noarch.rpm
      docker exec psmdb_pmm_{{ psmdb_version }}_{{ item }} dnf install -y https://repo.percona.com/yum/percona-release-latest.noarch.rpm
    loop: "{{ range(1, nodes_count | int + 1) | list }}"

  - name: Enable Percona Server for MongoDB repository
    shell: docker exec psmdb_pmm_{{ psmdb_version }}_{{ item }} percona-release enable psmdb-{{ psmdb_version | replace('_', '') }} release
    loop: "{{ range(1, nodes_count | int + 1) | list }}"

  - name: Install Percona Server for MongoDB
    shell: |
      docker exec psmdb_pmm_{{ psmdb_version }}_{{ item }} dnf install -y \
        percona-server-mongodb \
        percona-server-mongodb-tools \
        percona-server-mongodb-server \
        percona-server-mongodb-mongos \
        percona-mongodb-mongosh
    loop: "{{ range(1, nodes_count | int + 1) | list }}"

  - name: Start Percona Server for MongoDB
    shell: |
      docker exec psmdb_pmm_{{ psmdb_version }}_{{ item }} systemctl enable mongod
      docker exec psmdb_pmm_{{ psmdb_version }}_{{ item }} systemctl start mongod
    loop: "{{ range(1, nodes_count | int + 1) | list }}"

  - name: Wait 10 seconds for database to start
    pause:
      seconds: 10

  - name: Create pmm user inside of Percona Server for MongoDB
    shell: |
      docker exec psmdb_pmm_{{ psmdb_version }}_{{ item }} mongosh admin --eval 'db.createUser({user:"{{ pmm_user }}",pwd:"{{ pmm_user_password }}",roles:[{ role:"root",db:"admin" }]})'
    loop: "{{ range(1, nodes_count | int + 1) | list }}"

#  - name: Install and add pmm client.
#    include_tasks: ../tasks/install_pmm_client.yml
#    vars:
#      container_name: "psmdb_pmm_{{ psmdb_version }}_{{ item }}"
#    loop: "{{ range(1, nodes_count | int + 1) | list }}"

  - name: Get mongod user id
    shell: docker exec psmdb_pmm_{{ psmdb_version }}_1 id -u mongod
    register: mongod_userid

  - name: Set mongod user id
    set_fact:
      mongod_userid: "{{mongod_userid.stdout}}"

  - name: Create SSL certificates
    include_tasks: ../tasks/create_ssl_certificates.yml
    vars:
      container_name: "psmdb_pmm_{{ psmdb_version }}_{{ item }}"
    when: setup_type == "ssl"
    loop: "{{ range(1, nodes_count | int + 1) | list }}"

  - name: Create correct mongodb pem file
    shell: |
      cat ./ssl/server.crt ./ssl/server.key > ./ssl/mongodb.pem
      cat ./ssl/client.crt ./ssl/client.key > ./ssl/client.pem

  - name: Create correct mongodb pem file
    shell: docker cp ./data/mongod_ssl.conf psmdb_pmm_{{ psmdb_version }}_{{ item }}:/etc/mongod.conf
    loop: "{{ range(1, nodes_count | int + 1) | list }}"

  - name: Restart Percona Server for MongoDB with ssl config
    shell: docker exec psmdb_pmm_{{ psmdb_version }}_{{ item }} systemctl restart mongod
    loop: "{{ range(1, nodes_count | int + 1) | list }}"

  - name: Wait 10 seconds for database to start
    pause:
      seconds: 10

  - name: Verify ssl connection to mongodb
    shell: "docker exec psmdb_pmm_{{ psmdb_version }}_{{ item }} mongosh \"mongodb://127.0.0.1:27017/?tls=true\" --tlsCAFile /ssl/ca.crt --tlsCertificateKeyFile /ssl/client.pem --eval 'db.runCommand({ connectionStatus: 1 })'"
    loop: "{{ range(1, nodes_count | int + 1) | list }}"

