---
# Percona Server for MongoDB setup
- name: Setup Percona Server 8.4 and higher. Cluster with Group Replication in Docker
  hosts: localhost
  connection: local
  gather_facts: yes
  vars:
    psmdb_version: "{{ (lookup('env', 'PSMDB_VERSION') | default('7.0', true)) | replace('.', '_') }}"
    network_name: "pmm-qa"
    psmdb_container:
    nodes_count: "{{ (lookup('env', 'NODES_COUNT') | default('1', true)) | int }}"

  tasks:
  - name: Create pmm-qa network if not exist
    shell: docker network create {{ network_name }}
    ignore_errors: true

  - name: Prepare Container for Percona Server for MongoDB
    shell: |
      docker run --privileged --cgroupns=host -v /sys/fs/cgroup:/sys/fs/cgroup:ro -d --network={{ network_name }} --name="psmdb_pmm_{{ psmdb_version }}_{{ item }}" antmelekhin/docker-systemd:rockylinux-9
    loop: "{{ range(1, nodes_count | int + 1) | list }}"

  - name: Install Percona Release
    shell: |
      docker exec psmdb_pmm_{{ psmdb_version }}_{{ item }} wget https://repo.percona.com/yum/percona-release-latest.noarch.rpm
      docker exec psmdb_pmm_{{ psmdb_version }}_{{ item }} dnf install -y https://repo.percona.com/yum/percona-release-latest.noarch.rpm
    loop: "{{ range(1, nodes_count | int + 1) | list }}"

  - name: Enable Percona Server for MongoDB repository
    shell: docker exec psmdb_pmm_{{ psmdb_version }}_{{ item }} percona-release enable psmdb-{{ psmdb_version | replace('_', '') }} release
    loop: "{{ range(1, nodes_count | int + 1) | list }}"

  - name: Install Percona Server for MongoDB
    shell: docker exec psmdb_pmm_{{ psmdb_version }}_{{ item }} dnf install -y percona-server-mongodb
    loop: "{{ range(1, nodes_count | int + 1) | list }}"

  - name: Start Percona Server for MongoDB
    shell: |
      docker exec psmdb_pmm_{{ psmdb_version }}_{{ item }} systemctl enable mongod
      docker exec psmdb_pmm_{{ psmdb_version }}_{{ item }} systemctl start mongod
    loop: "{{ range(1, nodes_count | int + 1) | list }}"

