---
# Percona Server for MongoDB setup
- name: Setup Percona Server 8.4 and higher. Cluster with Group Replication in Docker
  hosts: localhost
  connection: local
  gather_facts: yes
  vars:
    psmdb_version: "{{ (lookup('env', 'PSMDB_VERSION') | default('7.0', true)) | replace('.', '_') }}"
    network_name: "pmm-qa"
    psmdb_container:
    nodes_count: "{{ (lookup('env', 'NODES_COUNT') | default('1', true)) | int }}"
    pmm_user: "pmm_mongodb"
    pmm_user_password: "5M](Q%q/U+YQ<^m"
    pmm_server_ip: "{{ lookup('vars', 'extra_pmm_server_ip', default=lookup('env','PMM_SERVER_IP') | default('127.0.0.1', true) ) }}"
    setup_type: "{{ lookup('env', 'MONGO_SETUP_TYPE') }}"

  tasks:
  - name: Create pmm-qa network if not exist
    shell: docker network create {{ network_name }}
    ignore_errors: true

  - name: Prepare Container for Percona Server for MongoDB
    shell: |
      docker run --rm -d --name="psmdb_pmm_{{ psmdb_version }}_{{ item }}" --privileged --cgroupns=host -v /sys/fs/cgroup:/sys/fs/cgroup:rw -v /var/lib/containerd antmelekhin/docker-systemd:rockylinux-9 journalctl -f
    loop: "{{ range(1, nodes_count | int + 1) | list }}"

  - name: Install Percona Release
    shell: |
      docker exec psmdb_pmm_{{ psmdb_version }}_{{ item }} wget https://repo.percona.com/yum/percona-release-latest.noarch.rpm
      docker exec psmdb_pmm_{{ psmdb_version }}_{{ item }} dnf install -y https://repo.percona.com/yum/percona-release-latest.noarch.rpm
    loop: "{{ range(1, nodes_count | int + 1) | list }}"

  - name: Enable Percona Server for MongoDB repository
    shell: docker exec psmdb_pmm_{{ psmdb_version }}_{{ item }} percona-release enable psmdb-{{ psmdb_version | replace('_', '') }} release
    loop: "{{ range(1, nodes_count | int + 1) | list }}"

  - name: Install Percona Server for MongoDB
    shell: docker exec psmdb_pmm_{{ psmdb_version }}_{{ item }} dnf install -y percona-server-mongodb
    loop: "{{ range(1, nodes_count | int + 1) | list }}"

  - name: Start Percona Server for MongoDB
    shell: |
      docker exec psmdb_pmm_{{ psmdb_version }}_{{ item }} systemctl enable mongod
      docker exec psmdb_pmm_{{ psmdb_version }}_{{ item }} systemctl start mongod
    loop: "{{ range(1, nodes_count | int + 1) | list }}"

  - name: Start Percona Server for MongoDB
    shell: |
      docker exec psmdb_pmm_{{ psmdb_version }}_{{ item }} mongosh admin --eval 'db.createUser({user:"{{ pmm_user }}",pwd:"{{ pmm_user_password }}",roles:[{ role:"root",db:"admin" }]})'
    loop: "{{ range(1, nodes_count | int + 1) | list }}"

  - name: Install and add pmm client.
    include_tasks: ../tasks/install_pmm_client.yml
    vars:
      container_name: "psmdb_pmm_{{ psmdb_version }}_{{ item }}"
    loop: "{{ range(1, nodes_count | int + 1) | list }}"

  - name: Create SSL certificates
    set_fact:
      nodes_count: 3
    when: setup_type == "ssl"