- name: Set default ssl_dir
  set_fact:
    ssl_dir: "./ssl"

- name: Create OpenSSL req config with dynamic CN
  copy:
    dest: ./ssl/openssl.cnf
    content: |
      [req]
      default_bits        = 2048
      default_keyfile     = privkey.pem
      distinguished_name  = req_distinguished_name
      x509_extensions     = v3_req
      prompt              = no

      [req_distinguished_name]
      C  = CZ
      ST = Prague
      L  = Prague
      O  = Percona
      OU = Percona Unit
      CN = localhost

      [v3_req]
      keyUsage            = digitalSignature, keyEncipherment
      extendedKeyUsage    = serverAuth
      subjectAltName      = @alt_names
      basicConstraints    = CA:FALSE

      [alt_names]
      DNS.1 = {{ container_name }}
      IP.1  = 127.0.0.1

- name: Create SSL certificates
  shell: |
    docker exec {{ container_name }} openssl genrsa -out /ssl/ca.key 2048
    docker exec {{ container_name }} openssl req -x509 -new -nodes -key /ssl/ca.key -sha256 -days 3650 -subj '/CN=CA' -out /ssl/ca.crt
    docker exec {{ container_name }} openssl genrsa -out /ssl/server.key 2048
    docker exec {{ container_name }} openssl req -new -key /ssl/server.key -config ./ssl/openssl.cnf -out /ssl/server.csr
    docker exec {{ container_name }} openssl x509 -req -in {{ ssl_dir }}/server.csr -CA /ssl/ca.crt -CAkey /ssl/ca.key -CAcreateserial -out /ssl/server.crt -days 365 -extensions v3_req -extfile /ssl/openssl.cnf
    docker exec {{ container_name }} openssl genrsa -out {{ ssl_dir }}/client.key 2048
    docker exec {{ container_name }} openssl req -new -key /ssl/client.key -subj '/CN=client' -out /ssl/client.csr
    docker exec {{ container_name }} openssl x509 -req -in /ssl/client.csr -CA {{ ssl_dir }}/ca.crt -CAkey {{ ssl_dir }}/ca.key -CAcreateserial -out /ssl/client.crt -days 365 -sha256

- name: Set permissions for cert files
  file:
    path: "{{ item.path }}"
    owner: "{{ item.owner }}"
    group: "{{ item.owner }}"
    mode: '0600'
  loop:
    - { path: "{{ ssl_dir }}/ca.crt", owner: "998" }
    - { path: "{{ ssl_dir }}/server.crt", owner: "998" }
    - { path: "{{ ssl_dir }}/server.key", owner: "998" }
    - { path: "{{ ssl_dir }}/client.key", owner: "998" }
    - { path: "{{ ssl_dir }}/client.crt", owner: "998" }
    - { path: "{{ ssl_dir }}/server.key", owner: "998" }
  become: yes
