---
- name: Deploy MinIO bucket.
  hosts: localhost
  connection: local
  gather_facts: no
  vars:
    network_name: "pmm-qa"
    buckets: "{{ lookup('env', 'BUCKETS') | default('bcp', true) | split(',') }}"
    minio_access_key: minio1234
    minio_secret_key: minio1234
    minio_volume_name: minio_backups
    minio_ports:
      - "9000:9000"
      - "9001:9001"

  tasks:
    - name: Create Docker network
      community.docker.docker_network:
        name: "{{ network_name }}"
        state: present
      ignore_errors: yes

    - name: Remove old MinIO docker container
      community.docker.docker_container:
        name: minio
        state: absent
      ignore_errors: yes

    - name: Remove MinIO Docker volume
      community.docker.docker_volume:
        name: "{{ minio_volume_name }}"
        state: absent
      ignore_errors: true

    - name: Create MinIO Docker volume
      community.docker.docker_volume:
        name: "{{ minio_volume_name }}"

    - name: Run MinIO container
      community.docker.docker_container:
        name: minio
        image: minio/minio
        restart_policy: unless-stopped
        ports: "{{ minio_ports }}"
        networks:
          - name: "{{ network_name }}"
        volumes:
          - "/tmp/minio/backups:/backups"
        env:
          MINIO_ACCESS_KEY: "{{ minio_access_key }}"
          MINIO_SECRET_KEY: "{{ minio_secret_key }}"
        command: server /backups --address :9000 --console-address :9001

    - name: Wait for MinIO to start
      wait_for:
        port: 9000
        host: "localhost"
        delay: 5
        timeout: 30

    - name: Run temporary mc container to create buckets
      vars:
        mc_cmd: >
          mc alias set myminio http://minio:9000 {{ minio_access_key }} {{ minio_secret_key }} &&
          {% for bucket in buckets %} mc mb myminio/{{ bucket }}; {% endfor %}
      community.docker.docker_container:
        name: "mc-setup"
        image: minio/mc
        networks:
          - name: "{{ network_name }}"
        entrypoint: /bin/sh
        command: -c "{{ mc_cmd }}"
        state: started
        auto_remove: true