- name: Copy a file into the container
  community.docker.docker_container_copy_into:
    container: "{{ container_name }}"
    path: ../pmm3-client-setup-centos.sh
    container_path: /pmm3-client-setup.sh

- name: "PMM Server IP is"
  debug:
    msg: "{{ pmm_server_ip }} is pmm server IP"

- name: Install pmm-client
  community.docker.docker_container_exec:
    container: "{{ container_name }}"
    user: "root"
    command: bash -x /pmm3-client-setup.sh --pmm_server_ip {{ pmm_server_ip }} --client_version {{ client_version }} --admin_password {{ admin_password }} --use_metrics_mode no
