---

- name: MySQL single, cluster with group Replication in Docker
  hosts: localhost
  connection: local
  gather_facts: yes
  vars:
    mysql_version: "{{ (lookup('env', 'MS_VERSION') | default('8.0', true)) | replace('.', '_') }}"
    replication_user: "repl_user"
    replication_password: "GRgrO9301RuF"
    root_password: "GRgrO9301RuF"
    mysql_port: 33066
    mysql_listen_port: 3306
    group_seeds_port: 34061
    nodes_count: "{{ (lookup('env', 'NODES_COUNT') | default('1', true)) | int }}"
    network_name: "pmm-qa"
    data_dir: "{{ lookup('env', 'HOME') }}/mysql_cluster_data"
    server_id_start: 1
    pmm_server_ip: "{{ lookup('vars', 'extra_pmm_server_ip', default=lookup('env','PMM_SERVER_IP') | default('127.0.0.1', true) ) }}"
    client_version: "{{ lookup('vars', 'extra_client_version', default=lookup('env','CLIENT_VERSION') | default('3-dev-latest', true) ) }}"
    admin_password: "{{ lookup('vars', 'extra_admin_password', default=lookup('env','ADMIN_PASSWORD') | default('admin', true) ) }}"
    query_source: "{{ lookup('env', 'QUERY_SOURCE') | default('perfschema', true) }}"
    metrics_mode: "{{ lookup('env', 'metrics_mode') }}"
    setup_type: "{{ lookup('env', 'SETUP_TYPE') }}"
    random_service_name_value: ""
    my_rocks: "{{ lookup('env', 'MY_ROCKS') | default(false, true) }}"
    container_prefix: "mysql_pmm{{ (setup_type|default('')) and '_' ~ setup_type }}_{{ mysql_version }}_"

  tasks:
#    - name: Fail if setup_type is gr or replication and version is less than 80
#      fail:
#        msg: "This setup_type ({{ setup_type }}) with version {{ mysql_version | replace('_', '.') }} is not supported!"
#      when: (setup_type == 'gr' or setup_type == 'replication') and (mysql_version | replace('_', '') | int < 80)

    - name: Modify the node count for group replication
      set_fact:
        nodes_count: 3
      when: nodes_count | int < 3 and setup_type == "gr"

    - name: Chance to correct nodes count for async replication
      set_fact:
        nodes_count: 2
      when: nodes_count | int < 2 and setup_type == "replication"

    - name: Create Docker network
      shell: docker network create {{ network_name }}
      ignore_errors: true

    - name: Remove old data folders
      shell: 'rm -fr {{ data_dir }}'
      loop: "{{ range(1, nodes_count | int + 1) | list }}"

    - name: Create data directories
      file:
        path: "{{ data_dir }}/node{{ item }}/data"
        state: directory
        mode: '0755'
      loop: "{{ range(1, nodes_count | int + 1) | list }}"

    - name: Recursively change ownership of a directory
      shell: "sudo chown -R 1001:1001 {{ data_dir }}/node{{ item }}/data"
      loop: "{{ range(1, nodes_count | int + 1) | list }}"

    - name: Setup MySQL group replication
      include_tasks: ./tasks/mysql-group-replication-setup.yml
      when: setup_type == "gr"

    - name: Setup MySQL with async replication
      include_tasks: ./tasks/mysql-async-replication-setup.yml
      when: setup_type == "replication"

    - name: Setup MySQL
      include_tasks: tasks/mysql-single.yml
      when: setup_type != "gr" and setup_type != "replication"

    - name: Wait 10 seconds for setup to finish
      pause:
        seconds: 10

    - name: Create slowlog configuration for mysql nodes
      shell: |
        docker exec {{ container_prefix }}{{ item }} mysql -uroot -p{{ root_password }} -e "SET GLOBAL slow_query_log='ON'; SET GLOBAL long_query_time=0;"
        docker exec {{ container_prefix }}{{ item }} mysql -uroot -p{{ root_password }} -e "SET GLOBAL log_slow_admin_statements=ON; SET GLOBAL log_slow_slave_statements=ON;"
      loop: "{{ range(1, nodes_count | int + 1) | list }}"
      when: query_source == "slowlog"

    - name: Install and add pmm client.
      include_tasks: ../tasks/install_pmm_client.yml
      vars:
        container_name: "{{ container_prefix }}{{ item }}"
      loop: "{{ range(1, nodes_count | int + 1) | list }}"

    - name: Generate random service name suffix
      set_fact:
        random_service_name_value: "_{{ 99999 | random + 1 }}"

    - name: Add service to pmm server
      shell: docker exec {{ container_prefix }}{{ item }} pmm-admin add mysql --query-source={{ query_source }} --username=root --password={{ root_password }} --environment=mysql-gr-dev --cluster=mysql-gr-dev-cluster --replication-set=mysql-gr-replication {{ container_prefix }}{{ item }}{{ random_service_name_value }} --debug 127.0.0.1:3306
      loop: "{{ range(1, nodes_count | int + 1) | list }}"
      when: setup_type == "gr"

    - name: Add service to pmm server
      shell: docker exec {{ container_prefix }}{{ item }} pmm-admin add mysql --query-source={{ query_source }} --username=root --password={{ root_password }} --environment=mysql-replication-dev --cluster=mysql-replication-dev-cluster --replication-set=mysql-async-replication {{ container_prefix }}{{ item }}{{ random_service_name_value }} --debug 127.0.0.1:3306
      loop: "{{ range(1, nodes_count | int + 1) | list }}"
      when: setup_type == "replication"

    - name: Add service to pmm server
      shell: docker exec {{ container_prefix }}{{ item }} pmm-admin add mysql --query-source={{ query_source }} --username=root --password={{ root_password }} --cluster=mysql-single-dev-cluster --environment=mysql-dev {{ container_prefix }}{{ item }}{{ random_service_name_value }} --debug 127.0.0.1:3306
      loop: "{{ range(1, nodes_count | int + 1) | list }}"
      when: setup_type != "gr" and setup_type != "replication"

    - name: Install sysbench inside of all mysql nodes
      shell: docker exec {{ container_prefix }}{{ item }} apt-get install -y sysbench
      loop: "{{ range(1, nodes_count | int + 1) | list }}"

    - name: Prepare sysbench inside of all mysql nodes
      shell: docker exec {{ container_prefix }}{{ item }} mysql -uroot -p{{ root_password }} -e "SET GLOBAL super_read_only = OFF; SET GLOBAL read_only = OFF;"
      loop: "{{ range(1, nodes_count | int + 1) | list }}"

    - name: Prepare sysbench inside of all mysql nodes
      shell: |
        docker exec {{ container_prefix }}{{ item }} mysql -uroot -p{{ root_password }} -e "CREATE DATABASE sbtest; CREATE USER 'sbtest'@'localhost' IDENTIFIED BY 'password';"
        docker exec {{ container_prefix }}{{ item }} mysql -uroot -p{{ root_password }} -e "GRANT ALL PRIVILEGES ON *.* TO 'sbtest'@'localhost'; CREATE USER 'sbtest'@'127.0.0.1' IDENTIFIED BY 'password';"
        docker exec {{ container_prefix }}{{ item }} mysql -uroot -p{{ root_password }} -e "GRANT ALL PRIVILEGES ON *.* TO 'sbtest'@'127.0.0.1'; FLUSH PRIVILEGES;"
      loop: "{{ range(1, nodes_count | int + 1) | list }}"
      when: setup_type != "gr" and setup_type != "replication" #and mysql_version | replace('_', '') | int >= 84

    - name: Prepare sysbench inside of primary mysql node
      shell: |
        docker exec {{ container_prefix }}1 mysql -uroot -p{{ root_password }} -e "CREATE DATABASE sbtest; CREATE USER 'sbtest'@'localhost' IDENTIFIED BY 'password';"
        docker exec {{ container_prefix }}1 mysql -uroot -p{{ root_password }} -e "GRANT ALL PRIVILEGES ON *.* TO 'sbtest'@'localhost'; CREATE USER 'sbtest'@'127.0.0.1' IDENTIFIED BY 'password';"
        docker exec {{ container_prefix }}1 mysql -uroot -p{{ root_password }} -e "GRANT ALL PRIVILEGES ON *.* TO 'sbtest'@'127.0.0.1'; FLUSH PRIVILEGES;"
      when: setup_type == "gr" or setup_type == "replication" # and mysql_version | replace('_', '') | int >= 84

    - name: Prepare data for sysbench inside of all mysql nodes
      shell: |
        docker exec {{ container_prefix }}{{ item }} sysbench /usr/share/sysbench/oltp_read_write.lua --mysql-host=127.0.0.1 --mysql-port=3306 --mysql-user=sbtest --mysql-password=password --mysql-db=sbtest --tables=10 --table-size=100000 --mysql-table-engine=InnoDB prepare
      when: setup_type != "gr" and setup_type != "replication"
      loop: "{{ range(1, nodes_count | int + 1) | list }}"

    - name: Prepare data for sysbench inside of first mysql nodes
      shell: docker exec {{ container_prefix }}1 sysbench /usr/share/sysbench/oltp_read_write.lua --mysql-host=127.0.0.1 --mysql-port=3306 --mysql-user=sbtest --mysql-password=password --mysql-db=sbtest --tables=10 --table-size=100000 --mysql-table-engine=InnoDB prepare
      when: setup_type == "gr" or setup_type == "replication"

    - name: Run load for sysbench inside of all mysql nodes
      shell: docker exec {{ container_prefix }}{{ item }} sysbench /usr/share/sysbench/oltp_read_write.lua --mysql-host=127.0.0.1 --mysql-port=3306 --mysql-user=sbtest --mysql-password=password --mysql-db=sbtest --tables=10 --table-size=100000 --threads=16 --time=60 --mysql-table-engine=InnoDB run
      loop: "{{ range(1, nodes_count | int + 1) | list }}"
      when: setup_type != "gr" and setup_type != "replication"

    - name: Run load for sysbench inside of primary mysql node
      shell: docker exec {{ container_prefix }}1 sysbench /usr/share/sysbench/oltp_read_write.lua --mysql-host=127.0.0.1 --mysql-port=3306 --mysql-user=sbtest --mysql-password=password --mysql-db=sbtest --tables=10 --table-size=100000 --threads=16 --time=60 --mysql-table-engine=InnoDB run
      when: setup_type == "gr" and setup_type == "replication"

    - name: Copy a load file into the container
      shell: docker cp ../data/mysql_load.sql {{ container_prefix }}{{ item }}:/mysql_load.sql
      loop: "{{ range(1, nodes_count | int + 1) | list }}"

    - name: Wait 10 seconds for node to be connected
      pause:
        seconds: 10

    - name: Run load inside of first mysql node
      shell: |
        docker exec {{ container_prefix }}1 mysql -uroot -p{{ root_password }} -e "CREATE DATABASE school;"
        docker exec {{ container_prefix }}1 sh -c "mysql -uroot -p{{ root_password }} school < /mysql_load.sql"
      when: setup_type in ['gr', 'replication'] and (mysql_version | replace('_','') | int) >= 80

    - name: Run load inside of all mysql nodes
      shell: |
        docker exec {{ container_prefix }}{{ item }} mysql -uroot -p{{ root_password }} -e "CREATE DATABASE school;"
        docker exec {{ container_prefix }}{{ item }} sh -c "mysql -uroot -p{{ root_password }} school < /mysql_load.sql"
      loop: "{{ range(1, nodes_count | int + 1) | list }}"
      when: setup_type not in ['gr', 'replication'] and (mysql_version | replace('_','') | int) >= 80