version: "3"
services:
  pmm-server:
    image: ${PMM_IMAGE:-perconalab/pmm-server:dev-latest}
    container_name: pmm-server
    environment:
      - "PMM_DEBUG=1"
      - "ENABLE_BACKUP_MANAGEMENT=1"
    ports:
      - "443:443"
      - "8081:80"
    networks:
      - qa-integration
    volumes:
      - pmm-server:/srv

  test:
    build:
      dockerfile: ./Dockerfile-testinfra
      context: .
    volumes:
      - ./test:/test
      - /var/run/docker.sock:/var/run/docker.sock:ro
    container_name: test
    hostname: test
    networks:
      - qa-integration

networks:
  qa-integration:
    external: true

volumes:
  pmm-server: null
  backups: null
