version: "3"
services:
  build_member:
    image: replica_member/local
    build:
      dockerfile: ./Dockerfile
      context: .
      args:
        - REPO=${REPO:-testing}
        - PBM_VERSION=${PBM_VERSION:-latest}
        - PSMDB_VERSION=${PSMDB_VERSION:-latest}
        - PMM_VERSION=${PMM_VERSION:-latest}
    command: /bin/bash

  rs101:
    depends_on:
      - build_member
    image: replica_member/local
    volumes:
      - ./conf/pbm:/etc/pbm
      - ./conf/mongod-rs:/etc/mongod
      - ./conf/datagen:/etc/datagen:ro
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: true
    environment:
      - "PBM_MONGODB_URI=mongodb://${PBM_USER:-pbm}:${PBM_PASS:-pbmpass}@127.0.0.1:27017"
      - "PMM_AGENT_SERVER_ADDRESS=pmm-server:443"
      - "PMM_AGENT_SERVER_USERNAME=admin"
      - "PMM_AGENT_SERVER_PASSWORD=password"
      - "PMM_AGENT_SERVER_INSECURE_TLS=1"
    container_name: rs101
    hostname: rs101
    networks:
      - rs1-network

  rs102:
    depends_on:
      - build_member
    image: replica_member/local
    volumes:
      - ./conf/pbm:/etc/pbm
      - ./conf/mongod-rs:/etc/mongod
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: true
    environment:
      - "PBM_MONGODB_URI=mongodb://${PBM_USER:-pbm}:${PBM_PASS:-pbmpass}@127.0.0.1:27017"
      - "PMM_AGENT_SERVER_ADDRESS=pmm-server:443"
      - "PMM_AGENT_SERVER_USERNAME=admin"
      - "PMM_AGENT_SERVER_PASSWORD=password"
      - "PMM_AGENT_SERVER_INSECURE_TLS=1"
    container_name: rs102
    hostname: rs102
    networks:
      - rs1-network

  rs103:
    depends_on:
      - build_member
    image: replica_member/local
    volumes:
      - ./conf/pbm:/etc/pbm
      - ./conf/mongod-rs:/etc/mongod
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: true
    environment:
      - "PBM_MONGODB_URI=mongodb://${PBM_USER:-pbm}:${PBM_PASS:-pbmpass}@127.0.0.1:27017"
      - "PMM_AGENT_SERVER_ADDRESS=pmm-server:443"
      - "PMM_AGENT_SERVER_USERNAME=admin"
      - "PMM_AGENT_SERVER_PASSWORD=password"
      - "PMM_AGENT_SERVER_INSECURE_TLS=1"
    container_name: rs103
    hostname: rs103
    networks:
      - rs1-network

  minio:
    image: minio/minio
    container_name: minio
    ports:
      - "9000:9000"
    networks:
      - rs1-network
    volumes:
      - backups:/backups
    environment:
      - "MINIO_ACCESS_KEY=minio1234"
      - "MINIO_SECRET_KEY=minio1234"
    command: server /backups

  createbucket:
    container_name: createbucket 
    image: minio/mc
    networks:
      - rs1-network
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c " sleep 5; /usr/bin/mc config host add myminio http://minio:9000 minio1234 minio1234; /usr/bin/mc mb myminio/bcp; exit 0; "

  pmm-server:
    image: ${PMM_IMAGE:-perconalab/pmm-server:dev-latest}
    container_name: pmm-server
    environment:
      - "PMM_DEBUG=1"
      - "ENABLE_BACKUP_MANAGEMENT=1"
    ports:
      - "443:443"
      - "8081:80"
    networks:
      - rs1-network
    volumes:
      - pmm-server:/srv

  test:
    build:
      dockerfile: ./Dockerfile-testinfra
      context: .
    volumes:
      - ./test:/test
      - /var/run/docker.sock:/var/run/docker.sock:ro
    container_name: test
    hostname: test
    networks:
      - rs1-network

networks:
  rs1-network:
    driver: bridge

volumes:
  pmm-server: null
  backups: null
