version: "3"
services:
  rs101:
    build:
      dockerfile: ./Dockerfile
      context: .
      args:
        - REPO=${REPO:-testing}
        - PBM_VERSION=${PBM_VERSION:-2.0.2-1}
        - PSMDB_VERSION=${PSMDB_VERSION:-6.0.2-1}
        - PMM_VERSION=${PMM_VERSION:-2.21.0-6}
    volumes:
      - ./conf/pbm:/etc/pbm
      - ./conf/mongod-rs:/etc/mongod
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: true
    environment:
      - "PBM_MONGODB_URI=mongodb://127.0.0.1:27017"
      - "PMM_AGENT_SERVER_ADDRESS=pmm-server:443"
      - "PMM_AGENT_SERVER_USERNAME=admin"
      - "PMM_AGENT_SERVER_PASSWORD=password"
      - "PMM_AGENT_SERVER_INSECURE_TLS=1"
    container_name: rs101
    hostname: rs101
    networks:
      - rs1-network

  rs102:
    build:
      dockerfile: ./Dockerfile
      context: .
      args:
        - REPO=${REPO:-testing}
        - PBM_VERSION=${PBM_VERSION:-2.0.2-1}
        - PSMDB_VERSION=${PSMDB_VERSION:-6.0.2-1}
        - PMM_VERSION=${PMM_VERSION:-2.21.0-6}
    volumes:
      - ./conf/pbm:/etc/pbm
      - ./conf/mongod-rs:/etc/mongod
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: true
    environment:
      - "PBM_MONGODB_URI=mongodb://127.0.0.1:27017"
      - "PMM_AGENT_SERVER_ADDRESS=pmm-server:443"
      - "PMM_AGENT_SERVER_USERNAME=admin"
      - "PMM_AGENT_SERVER_PASSWORD=password"
      - "PMM_AGENT_SERVER_INSECURE_TLS=1"
    container_name: rs102
    hostname: rs102
    networks:
      - rs1-network

  rs103:
    build:
      dockerfile: ./Dockerfile
      context: .
      args:
        - REPO=${REPO:-testing}
        - PBM_VERSION=${PBM_VERSION:-2.0.2-1}
        - PSMDB_VERSION=${PSMDB_VERSION:-6.0.2-1}
        - PMM_VERSION=${PMM_VERSION:-2.21.0-6}
    volumes:
      - ./conf/pbm:/etc/pbm
      - ./conf/mongod-rs:/etc/mongod
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: true
    environment:
      - "PBM_MONGODB_URI=mongodb://127.0.0.1:27017"
      - "PMM_AGENT_SERVER_ADDRESS=pmm-server:443"
      - "PMM_AGENT_SERVER_USERNAME=admin"
      - "PMM_AGENT_SERVER_PASSWORD=password"
      - "PMM_AGENT_SERVER_INSECURE_TLS=1"
    container_name: rs103
    hostname: rs103
    networks:
      - rs1-network

  rs1-init:
    image: perconalab/percona-server-mongodb:6.0.2
    container_name: rs1-init
    restart: "no"
    container_name: rs1-init
    networks:
      - rs1-network
    depends_on:
      - rs101
      - rs102
      - rs103
    command: >
      mongosh --host rs101:27017 --eval 
      '
      config = {
      "_id" : "rs",
      "members" : [
        {
          "_id" : 0,
          "host" : "rs101:27017"
        },
        {
          "_id" : 1,
          "host" : "rs102:27017"
        },
        {
          "_id" : 2,
          "host" : "rs103:27017"
        }
      ]
      };
      rs.initiate(config);
      ' 

  minio:
    image: minio/minio
    container_name: minio
    ports:
      - "9000:9000"
    networks:
      - rs1-network
    volumes:
      - backups:/backups
    environment:
      - "MINIO_ACCESS_KEY=minio1234"
      - "MINIO_SECRET_KEY=minio1234"
    command: server /backups

  createbucket:
    container_name: createbucket 
    image: minio/mc
    networks:
      - rs1-network
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c " sleep 5; /usr/bin/mc config host add myminio http://minio:9000 minio1234 minio1234; /usr/bin/mc mb myminio/bcp; exit 0; "

  pmm-server:
    image: ${PMM_IMAGE:-perconalab/pmm-server:dev-latest}
    container_name: pmm-server
    environment:
      - "PMM_DEBUG=1"
      - "ENABLE_BACKUP_MANAGEMENT=1"
    ports:
      - "443:443"
      - "8081:80"
    networks:
      - rs1-network
    volumes:
      - pmm-server:/srv

networks:
  rs1-network:
    driver: bridge

volumes:
  pmm-server: null
  backups: null
