- name: Prepare Container for MySQL 8.0+
  shell: |
    docker run --rm -d --name="{{ container_prefix }}{{ item }}" \
      --network="pmm-qa" \
      --privileged --cgroupns=host -v /sys/fs/cgroup:/sys/fs/cgroup:rw \
      -v /var/lib/containerd \
      -v ./ssl:/ssl \
      antmelekhin/docker-systemd:ubuntu-24.04
  when: mysql_version | replace('_', '') | int >= 80
  loop: "{{ range(1, nodes_count | int + 1) | list }}"

- name: Prepare Container for MySQL 5.7
  shell: |
    docker run --rm -d --name="{{ container_prefix }}{{ item }}" \
      --network="pmm-qa" \
      --privileged --cgroupns=host -v /sys/fs/cgroup:/sys/fs/cgroup:rw \
      -v /var/lib/containerd \
      -v ./ssl:/ssl \
      antmelekhin/docker-systemd:ubuntu-22.04
  when: mysql_version | replace('_', '') | int < 80
  loop: "{{ range(1, nodes_count | int + 1) | list }}"

- name: Install dependencies
  shell: |
    docker exec {{ container_prefix }}{{ item }} apt-get update
    docker exec {{ container_prefix }}{{ item }} apt-get -y install wget gnupg2 lsb-release curl
  loop: "{{ range(1, nodes_count | int + 1) | list }}"

- name: Download Mysql APT Repo package
  shell: |
    docker exec {{ container_prefix }}{{ item }} wget -O mysql-apt.deb https://dev.mysql.com/get/mysql-apt-config_0.8.36-1_all.deb
    docker exec {{ container_prefix }}{{ item }} dpkg -i ./mysql-apt.deb
    docker exec {{ container_prefix }}{{ item }} apt-get update
  loop: "{{ range(1, nodes_count | int + 1) | list }}"
  when: mysql_version | replace('_', '') | int >= 80

- name: Install MySQL 5.7
  shell: |
    docker exec {{ container_prefix }}{{ item }} wget -q -O mysql.tar.gz https://downloads.mysql.com/archives/get/p/23/file/mysql-5.7.44-linux-glibc2.12-x86_64.tar.gz > /dev/null
    docker exec {{ container_prefix }}{{ item }} groupadd mysql > /dev/null
    docker exec {{ container_prefix }}{{ item }} useradd -r -g mysql -s /bin/false mysql > /dev/null
    docker exec {{ container_prefix }}{{ item }} tar zxvf mysql.tar.gz > /dev/null
    docker exec {{ container_prefix }}{{ item }} mv mysql-5.7.44-linux-glibc2.12-x86_64 /usr/local/mysql > /dev/null
    docker exec {{ container_prefix }}{{ item }} ln -s /usr/local/mysql-5.7.44-linux-glibc2.12-x86_64 mysql > /dev/null
    docker exec {{ container_prefix }}{{ item }} chown -R mysql:mysql /usr/local/mysql > /dev/null
    docker exec {{ container_prefix }}{{ item }} mkdir /usr/local/mysql/data > /dev/null
    docker exec {{ container_prefix }}{{ item }} chown mysql:mysql /usr/local/mysql/data > /dev/null
  loop: "{{ range(1, nodes_count | int + 1) | list }}"
  when: mysql_version | replace('_', '') | int == 57


#docker exec {{ container_prefix }}{{ item }} bin/mysqld --initialize --user=mysql --basedir=/usr/local/mysql --datadir=/usr/local/mysql/data > /dev/null
#  docker exec {{ container_prefix }}{{ item }} cp support-files/mysql.server /etc/init.d/mysql > /dev/null
#  docker exec {{ container_prefix }}{{ item }} chmod +x /etc/init.d/mysql > /dev/null
#  docker exec {{ container_prefix }}{{ item }} export PATH=/usr/local/mysql/bin:$PATH > /dev/null
#  docker exec {{ container_prefix }}{{ item }} source ~/.bashrc > /dev/null

- name: Fail if setup_type is gr or replication and version is less than 80
  fail:
    msg: "This setup_type ({{ setup_type }}) with version {{ mysql_version | replace('_', '.') }} is not supported!"

- name: Set MySQl server package name to install
  shell: docker exec {{ container_prefix }}1 apt-cache policy mysql-server | grep {{ mysql_version | replace('_', '.') }} | head -n1 | awk '{print $1}'
  register: mysql_server_package_name

- name: Set MySQl server package name to install
  set_fact:
    mysql_server_package_name: "{{ mysql_server_package_name.stdout }}"

- name: Set MySQl common package name to install
  shell: docker exec {{ container_prefix }}1 apt-cache policy mysql-common | grep {{  '5.8' if mysql_version | replace('_', '') == '57' else mysql_version | replace('_', '.') }} | head -n1 | awk '{print $1}'
  register: mysql_common_package_name

- name: Set MySQl common package name to install
  set_fact:
    mysql_common_package_name: "{{ mysql_common_package_name.stdout }}"

- name: Install MySQL
  shell: |
    docker exec {{ container_prefix }}{{ item }} apt-get install -y \
      mysql-common={{ mysql_common_package_name }} \
      mysql-server{{ '-5.7' if mysql_version | replace('_', '') == '57' else '' }}={{ mysql_server_package_name }} \
      mysql-client{{ '-5.7' if mysql_version | replace('_', '') == '57' else '' }}={{ mysql_server_package_name }} \
      mysql-server-core{{ '-5.7' if mysql_version | replace('_', '') == '57' else '' }}={{ mysql_server_package_name }}
  loop: "{{ range(1, nodes_count | int + 1) | list }}"
  when: mysql_version | replace('_', '') | int >= 80