- name: Prepare Container for MySQL 8.0+
  shell: |
    docker run --rm -d --name="{{ container_prefix }}{{ item }}" \
      --network="pmm-qa" \
      --privileged --cgroupns=host -v /sys/fs/cgroup:/sys/fs/cgroup:rw \
      -v /var/lib/containerd \
      -v ./ssl:/ssl \
      antmelekhin/docker-systemd:ubuntu-24.04
  when: ms_version | replace('_', '') | int >= 80
  loop: "{{ range(1, nodes_count | int + 1) | list }}"

- name: Prepare Container for MySQL 5.7
  shell: |
    docker run --rm -d --name="{{ container_prefix }}{{ item }}" \
      --network="pmm-qa" \
      --privileged --cgroupns=host -v /sys/fs/cgroup:/sys/fs/cgroup:rw \
      -v /var/lib/containerd \
      -v ./ssl:/ssl \
      antmelekhin/docker-systemd:ubuntu-18.04
  when: ms_version | replace('_', '') | int < 80
  loop: "{{ range(1, nodes_count | int + 1) | list }}"

- name: Install dependencies
  shell: |
    docker exec {{ container_prefix }}{{ item }} apt-get update
    docker exec {{ container_prefix }}{{ item }} apt-get -y install wget gnupg2 lsb-release curl
  loop: "{{ range(1, nodes_count | int + 1) | list }}"

- name: Download Mysql APT Repo package
  shell: |
    docker exec {{ container_prefix }}{{ item }} wget -O mysql-apt.deb https://dev.mysql.com/get/mysql-apt-config_0.8.10-1_all.deb
    docker exec {{ container_prefix }}{{ item }} wget https://repo.mysql.com/RPM-GPG-KEY-mysql-2022 -O /etc/apt/keyrings/mysql.asc
    docker exec {{ container_prefix }}{{ item }} apt-key adv --keyserver keyserver.ubuntu.com --recv-keys B7B3B788A8D3785C
    docker exec {{ container_prefix }}{{ item }} dpkg -i ./mysql-apt.deb
    docker exec {{ container_prefix }}{{ item }} apt-get update
  loop: "{{ range(1, nodes_count | int + 1) | list }}"

- name: Set MySQl package name to install
  shell: docker exec {{ container_prefix }}1 apt-cache policy mysql-server | grep {{ ms_version | replace('_', '.') }} | head -n1 | awk '{print $1}'
  register: mysql_package_name

- name: Set MySQl package name to install
  set_fact:
    mysql_package_name: "{{ mysql_package_name.stdout }}"

- name: Install MySQL
  shell:
    docker exec {{ container_prefix }}{{ item }} apt-get update
    docker exec {{ container_prefix }}{{ item }} apt-get install -y mysql-server={{ mysql_package_name }}
  loop: "{{ range(1, nodes_count | int + 1) | list }}"