- name: Start Percona Server containers
  community.docker.docker_container:
    name: "ps_pmm_{{ ps_version }}_{{ item }}"
    image: "percona/percona-server:{{ ps_version }}"
    restart_policy: always
    state: started
    networks:
      - name: "{{ network_name }}"
    env:
      MYSQL_ROOT_PASSWORD: "{{ root_password }}"
    ports:
      - "{{ mysql_port + item - 1 }}:{{ mysql_listen_port }}"
      - "{{ group_seeds_port + item - 1 }}:{{ group_seeds_port }}"
    volumes:
      - "{{ data_dir }}/node{{ item }}/data:/var/lib/mysql"
  loop: "{{ range(1, nodes_count | int + 1) | list }}"

- name: Wait for MySQL to be available
  wait_for:
    host: localhost
    port: "{{ mysql_port + item - 1 }}"
    delay: 10
    timeout: 300
  loop: "{{ range(1, nodes_count | int + 1) | list }}"
