name: PMM_PDPGSQL
on:
  workflow_dispatch:
    inputs:
      pdpgsql_version:
        description: "PDPGSQL Version available Image versions on github, example: 15, 16, 17"
        required: true
        default: '17'
        type: string
      pmm_qa_branch:
        description: "Branch for qa-integration to checkout"
        required: false
        type: string
      pmm_ui_tests_branch:
        description: "Branch for PMM-UI tests to checkout"
        required: false
        type: string
      pmm_server_image:
        description: "pmm_image, example: perconalab/pmm-server:3-dev-latest"
        default: 'perconalab/pmm-server:3-dev-latest'
        required: false
        type: string
      pmm_client_version:
        description: 'PMM Client version (3-dev-latest|pmm3-rc|x.xx.x|https...)'
        default: '3-dev-latest'
        required: false
        type: string
  push:
    branches:
      - v3

  pull_request:
    branches:
      - v3

jobs:
  PMM_PDPGSQL_TEST:
    runs-on: ubuntu-22.04
    timeout-minutes: 40
    env:
      ADMIN_PASSWORD: 'admin'
      PDPGSQL_VERSION: ${{ github.event.inputs.pdpgsql_version || '17' }}
      PMM_IMAGE: ${{ github.event.inputs.pmm_server_image || 'perconalab/pmm-server:3-dev-latest' }}
      PMM_QA_BRANCH: ${{ github.event.inputs.pmm_qa_branch || 'v3' }}
      PMM_UI_BRANCH: ${{ github.event.inputs.pmm_ui_tests_branch || 'v3' }}
      PMM_CLIENT_VERSION: ${{ github.event.inputs.pmm_client_version || '3-dev-latest' }}

    steps:
    - uses: actions/checkout@v2

    - name: Run the PMM Server container
      run: docker run --detach --restart always -p 443:8443 -p 8081:8080 --name pmm-server ${{ env.PMM_IMAGE }}

    - name: Checkout qa-integration repo
      uses: actions/checkout@v4
      with:
        ref: ${{ env.PMM_QA_BRANCH }}
        repository: Percona-Lab/qa-integration
        path: ./qa-integration

    - name: Export path to qa-integration repo
      working-directory: qa-integration
      run: echo "PATH_TO_PMM_QA=$(pwd)" >> $GITHUB_ENV

    - name: Run Setup for E2E Tests
      working-directory: qa-integration/pmm_qa
      run: |
        mkdir -m 777 -p /tmp/backup_data
        python3 -m venv virtenv
        . virtenv/bin/activate
        pip install --upgrade pip
        pip install --force-reinstall -U setuptools
        pip install -r requirements.txt
        python pmm-framework.py --verbose --pmm-server-password=${{ env.ADMIN_PASSWORD }} --client-version=${{ env.PMM_CLIENT_VERSION }} --database PDPGSQL=${{ env.PDPGSQL_VERSION }}

    - name: Checkout PMM UI tests
      uses: actions/checkout@v4
      with:
        ref: ${{ env.PMM_UI_BRANCH }}
        repository: percona/pmm-ui-tests
        path: ./pmm-ui-tests

    - name: Install npx dependencies
      run: npm ci && npx playwright install --with-deps && npx codeceptjs def pr.codecept.js
      working-directory: pmm-ui-tests
      
    - name: Run the Integration tests of pdpgsql
      working-directory: pmm-ui-tests
      run: |
        export PMM_UI_URL="http://127.0.0.1:8081/"
        npx codeceptjs run -c pr.codecept.js tests/qa-integration/pmm_pdpgsql_integration_test.js
