name: PMM_PSMDB_PBM_FULL

on:
  workflow_dispatch:
    inputs:
      pmm_version:
        description: "pmm2-client version"
        default: "3-dev-latest"
        required: false
      pmm_image:
        description: "pmm-server docker image"
        default: "perconalab/pmm-server:3-dev-latest"
        required: false

  push:
    branches:
      - main
      - v3

  pull_request:
    branches:
      - main
      - v3

jobs:
  test_replica_set:
    runs-on: ubuntu-22.04
    timeout-minutes: 20
    strategy:
      fail-fast: false
      matrix:
        psmdb: ["6.0", "7.0", "8.0"]
    env:
      PMM_CLIENT_VERSION: ${{ inputs.pmm_version || '3-dev-latest' }}
      PMM_IMAGE: ${{ inputs.pmm_image || 'perconalab/pmm-server:3-dev-latest' }}
    steps:
    - uses: actions/checkout@v2
    - name: Test RS with PSMDB ${{ matrix.psmdb }}
      run: |
        PSMDB_VERSION=${{ matrix.psmdb }} ./start-rs.sh
      working-directory: ./pmm_psmdb-pbm_setup

  test_sharded_cluster:
    runs-on: ubuntu-22.04
    timeout-minutes: 20
    strategy:
      fail-fast: false
      matrix:
        psmdb: ["6.0", "7.0", "8.0"]
    env:
      PMM_CLIENT_VERSION: ${{ inputs.pmm_version || '3-dev-latest' }}
      PMM_IMAGE: ${{ inputs.pmm_image || 'perconalab/pmm-server:3-dev-latest' }}
    steps:
    - uses: actions/checkout@v2
    - name: Test sharded with PSMDB ${{ matrix.psmdb }}
      run: |
        PSMDB_VERSION=${{ matrix.psmdb }} ./start-sharded.sh
      working-directory: ./pmm_psmdb-pbm_setup

  test_diff_auth:
    runs-on: ubuntu-22.04
    timeout-minutes: 20
    strategy:
      fail-fast: false
      matrix:
        psmdb: ["6.0", "7.0", "8.0"]
    env:
      PMM_CLIENT_VERSION: ${{ inputs.pmm_version || '3-dev-latest' }}
      PMM_IMAGE: ${{ inputs.pmm_image || 'perconalab/pmm-server:3-dev-latest' }}
    steps:
    - uses: actions/checkout@v3
    - name: Test auth with PSMDB ${{ matrix.psmdb }}
      run: |
        PSMDB_VERSION=${{ matrix.psmdb }} ./test-auth.sh
      working-directory: ./pmm_psmdb_diffauth_setup
