name: PMM_PD-PGSQL
on:
  workflow_dispatch:
    inputs:
      pg_version:
        description: "Percona Distributed PostgreSQL version"
        required: true
      server_image:
        description: "pmm_image, example: perconalab/pmm-server:dev-latest"
        required: false
      client_image:
        description: "pmm client image, example: perconalab/pmm-client:dev-latest"
        required: false
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  EnvSetup:
    name: Setup Dynamic Environment Variables
    runs-on: ubuntu-latest
    timeout-minutes: 1
    outputs:
      pg-version: ${{ steps.pg-version.outputs.result }}
    steps:
      - name: Set PG version
        id: pg-version
        shell: bash
        run: echo "result={{ inputs.pg_version || 14}}" >> "$GITHUB_OUTPUT"

  PMM_PD-PGSQL_TEST:
    needs: [EnvSetup]
    uses: Percona-Lab/pmm-submodules/.github/workflows/ui-tests.yml
    secrets: inherit
    with:
      server_image: ${{ inputs.server_image || 'perconalab/pmm-server:dev-latest' }}
      client_version: ${{ inputs.client_version || 'dev-latest' }}
      client_image: ${{ inputs.client_image || 'perconalab/pmm-client:dev-latest' }}
      pmm_qa_branch: ${{ inputs.pmm_qa_branch || 'main' }}
      pmm_ui_branch: ${{ inputs.pmm_ui_branch || 'main' }}
      sha: ${{ inputs.sha || github.event.pull_request.head.sha ||  'null' }}
      client_flags: '--addclient=pdpgsql,1'
      tags_for_tests: '@pmm-pd-pgsql-integration'
