name: PMM_PS
on:
  workflow_dispatch:
    inputs:
      ps_version:
        description: "ps version"
        required: true
      pmm_image:
        description: "pmm_image"
        required: false
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  test_pmm_ps:
    runs-on: ubuntu-20.04
    timeout-minutes: 20
    env:
      PS_VERSION: ${{ github.event.inputs.ps_version || '8.0.33-25' }}
      PMM_IMAGE: ${{ github.event.inputs.pmm_image || 'perconalab/pmm-server:dev-latest' }}
    steps:
    - uses: actions/checkout@v2
    
    - name: Install Ansible and update the node
      run: sudo apt-get update -y && sudo apt-get install ansible -y

    - name: Install Percona Release Package
      run: wget https://repo.percona.com/apt/percona-release_latest.generic_all.deb && sudo dpkg -i percona-release_latest.generic_all.deb
     
    - name: Install Enable percona-release experimental for dev-latest installation of pmm2-client
      run: sudo percona-release enable-only original experimental
     
    - name: Install PMM Client 
      run: sudo apt update -y && sudo apt install -y pmm2-client

    - name: test-pmm-ps
      run: |
           chmod +x start-pmm-ps.sh && ./start-pmm-ps.sh
      working-directory: ./pmm_ps_setup
