name: qa-integration-results
on:
  workflow_dispatch:
    inputs:
      job_name:
        description: "Name of the Job for generating summary"
        required: true
        type: string

jobs:
  qa-integration-results:
    name: "Generate Integration Job execution results"
    runs-on: ubuntu-20.04
    timeout-minutes: 10
    env:
      PK_GITHUB_TOKEN: ${{ secrets.PK_GITHUB_TOKEN }}
      JOB_NAME: ${{ inputs.job_name || 'PMM_PS' }}

    steps:
      - uses: actions/checkout@v2
      - name: Setup tools
        run: |
          ls -la
          chmod +x qa_integration_results.py
          python ./qa_integration_results.py

      - uses: actions/upload-artifact@v4
        if: ${{ always() }}
        with:
          name: Attach Results output
          path: |
            results/workflow_runs_${{ env.JOB_NAME }}.csv
